version: "3"
services:
  app:
    build: .
    environment:
      - PORT
      - DATABASE_URL=postgres://postgres:password@sql:5432/board
      - REDIS_URL=redis://redis
    links:
      - redis
      - sql
    # network_mode: bridge
    networks:
      - app_network
    ports:
      - $PORT:$PORT
    volumes:
      - ./share/library:/app/share/library
  redis:
    image: redis:7.2-alpine
    networks:
      - app_network
  sql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: board
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    # network_mode: bridge
    networks:
      - app_network
    # https://stackoverflow.com/questions/66892446/signal-11-segmentation-fault-error-after-switching-postgresql-alpine-image-to
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./packages/sql/initdb.d:/docker-entrypoint-initdb.d

networks:
  app_network:
    external: true
