version: "3"
services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@sql:5432/board
    links:
      - sql
    network_mode: bridge
  sql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: board
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    network_mode: bridge
    volumes:
      - ./packages/sql/initdb.d:/docker-entrypoint-initdb.d
