version: "3"
services:
  app:
    build: .
    environment:
      - PORT
      - DATABASE_URL=postgres://postgres:password@sql:5432/board
      - MQTT_URL=mqtt://mqtt
      - REDIS_URL=redis://redis
    links:
      - mqtt
      - redis
      - sql
    # network_mode: host
    # network_mode: bridge
    networks:
      - app_network
    ports:
      - $PORT:$PORT
    restart: unless-stopped
    volumes:
      - ./share/library:/app/share/library
    devices:
      - /dev/snd:/dev/snd
  cast:
    build: packages/cast
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - MQTT_URL=mqtt://localhost
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
  # mqtt:
  #   image: emqx:5.4
  #   networks:
  #     - app_network
  #   ports:
  #     - 1883:1883
  #     - 8083:8083
  #     - 8084:8084
  #     - 8883:8883
  #     - 18083:18083
  #   restart: unless-stopped
  mqtt:
    image: eclipse-mosquitto:2.0
    networks:
      - app_network
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    user: 1883:996
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      # - ./mosquitto/data:/mosquitto/data
      # - ./mosquitto/log:/mosquitto/log
  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    networks:
      - app_network
  sql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: board
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    # network_mode: bridge
    networks:
      - app_network
    restart: unless-stopped
    # https://stackoverflow.com/questions/66892446/signal-11-segmentation-fault-error-after-switching-postgresql-alpine-image-to
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./packages/sql/initdb.d:/docker-entrypoint-initdb.d

networks:
  app_network:
    external: true
