import { z } from "zod";

export const Schema = z.object({
  state: z.object({
    on: z.boolean(),
    bri: z.number(),
    transition: z.number(),
    ps: z.number(),
    pl: z.number(),
    ledmap: z.number(),
    AudioReactive: z.object({ on: z.boolean() }),
    nl: z.object({
      on: z.boolean(),
      dur: z.number(),
      mode: z.number(),
      tbri: z.number(),
      rem: z.number(),
    }),
    udpn: z.object({
      send: z.boolean(),
      recv: z.boolean(),
      sgrp: z.number(),
      rgrp: z.number(),
    }),
    lor: z.number(),
    mainseg: z.number(),
    seg: z
      .object({
        id: z.number(),
        start: z.number(),
        stop: z.number(),
        len: z.number(),
        grp: z.number(),
        spc: z.number(),
        of: z.number(),
        on: z.boolean(),
        frz: z.boolean(),
        bri: z.number(),
        cct: z.number(),
        set: z.number(),
        col: z.array(z.array(z.number())),
        fx: z.number(),
        sx: z.number(),
        ix: z.number(),
        pal: z.number(),
        c1: z.number(),
        c2: z.number(),
        c3: z.number(),
        sel: z.boolean(),
        rev: z.boolean(),
        mi: z.boolean(),
        o1: z.boolean(),
        o2: z.boolean(),
        o3: z.boolean(),
        si: z.number(),
        m12: z.number(),
      })
      .array(),
  }),
  info: z.object({
    ver: z.string(),
    vid: z.number(),
    cn: z.string(),
    release: z.string(),
    repo: z.string(),
    deviceId: z.string(),
    leds: z.object({
      count: z.number(),
      pwr: z.number(),
      fps: z.number(),
      maxpwr: z.number(),
      maxseg: z.number(),
      bootps: z.number(),
      seglc: z.number().array(),
      lc: z.number(),
      rgbw: z.boolean(),
      wv: z.number(),
      cct: z.number(),
    }),
    str: z.boolean(),
    name: z.string(),
    udpport: z.number(),
    simplifiedui: z.boolean(),
    live: z.boolean(),
    liveseg: z.number(),
    lm: z.string(),
    lip: z.string(),
    ws: z.number(),
    fxcount: z.number(),
    palcount: z.number(),
    cpalcount: z.number(),
    maps: z.object({ id: z.number() }).array(),
    wifi: z.object({
      bssid: z.string(),
      rssi: z.number(),
      signal: z.number(),
      channel: z.number(),
      ap: z.boolean(),
    }),
    fs: z.object({ u: z.number(), t: z.number(), pmt: z.number() }),
    ndc: z.number(),
    arch: z.string(),
    core: z.string(),
    clock: z.number(),
    flash: z.number(),
    lwip: z.number(),
    bootloaderSHA256: z.string(),
    freeheap: z.number(),
    uptime: z.number(),
    time: z.string(),
    u: z.object({ AudioReactive: z.string().array() }),
    opt: z.number(),
    brand: z.string(),
    product: z.string(),
    mac: z.string(),
    ip: z.string(),
  }),
  effects: z.string().array(),
  palettes: z.string().array(),
});

export type SchemaType = z.infer<typeof Schema>;
